export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';

export const ADD_PRODUCTUSER = 'ADD_PRODUCTUSER';
export const GET_PRODUCTUSERS = 'GET_PRODUCTUSERS';
export const GET_PRODUCTUSER = 'GET_PRODUCTUSER';